<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="WatchdogTimer" Id="{ea05dca4-2630-471a-814d-f1294ce390fd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK WatchdogTimer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="WatchdogTimer">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>